from pathlib import Path

from core.services import schema_service


class RecordingCursor:
    def __init__(self):
        self.statements = []

    def execute(self, sql, params=None):
        self.statements.append(str(sql))


def test_postgres_competencia_schema_uses_postgres_ddl():
    cursor = RecordingCursor()
    schema_service._migrar_competencia_postgres(object(), cursor)
    sql = "\n".join(cursor.statements)

    assert "competencia_pendiente" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "AUTOINCREMENT" not in sql
    assert "ADD COLUMN IF NOT EXISTS retador_codigo" in sql


def test_supabase_competencia_migration_is_idempotent_and_non_destructive():
    path = (
        Path(__file__).resolve().parents[2]
        / "supabase"
        / "migrations"
        / "20260908000100_competencia_schema_postgres.sql"
    )
    sql = path.read_text(encoding="utf-8")

    assert "BEGIN;" in sql and "COMMIT;" in sql
    assert "CREATE TABLE IF NOT EXISTS public.competencia_pendiente" in sql
    assert "ADD COLUMN IF NOT EXISTS tipo" in sql
    assert "DROP TABLE" not in sql
    assert "DROP COLUMN" not in sql
