"""Migración Grupo Madre en el init de Postgres: ADD COLUMN IF NOT EXISTS tipo."""
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock

from core.services import schema_service


class RecordingCursor:
    def __init__(self):
        self.statements = []

    def execute(self, sql, params=None):
        self.statements.append(str(sql))

    def fetchone(self):
        return None

    def fetchall(self):
        return []


def test_migrar_grupo_madre_v1_postgres_adds_tipo_if_not_exists():
    cursor = RecordingCursor()
    schema_service._migrar_grupo_madre_v1_postgres(cursor)
    sql = "\n".join(cursor.statements)

    assert "ADD COLUMN IF NOT EXISTS tipo" in sql
    assert "ADD COLUMN IF NOT EXISTS grupo_madre_id" in sql
    assert "AUTOINCREMENT" not in sql
    assert "INSERT OR IGNORE" not in sql
    assert "ON CONFLICT (codigo_postal) DO NOTHING" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql


def test_migrar_grupo_madre_v1_si_procede_usa_ddl_postgres():
    cursor = RecordingCursor()
    db = SimpleNamespace(backend="postgres")
    schema_service._migrar_grupo_madre_v1_si_procede(db, None, cursor)
    sql = "\n".join(cursor.statements)

    assert "ADD COLUMN IF NOT EXISTS tipo" in sql
    assert any("INSERT INTO migraciones" in s for s in cursor.statements)


def test_migrar_cp_auto_split_v1_postgres_if_not_exists():
    cursor = RecordingCursor()
    db = SimpleNamespace(backend="postgres")
    schema_service._migrar_cp_auto_split_v1_si_procede(db, None, cursor)
    sql = "\n".join(cursor.statements)
    assert "ADD COLUMN IF NOT EXISTS aliados_desde_ultimo_grupo" in sql


def test_init_postgres_schema_commits_madre_v1_antes_de_consolidar():
    src = Path(schema_service.__file__).read_text(encoding="utf-8")
    idx = src.index("def _init_postgres_schema")
    block = src[idx : idx + 9000]
    v1_idx = block.index("_migrar_grupo_madre_v1_si_procede")
    split_idx = block.index("_migrar_cp_auto_split_v1_si_procede")
    v2_idx = block.index("_migrar_grupo_madre_v2_consolidar_si_procede")
    assert v1_idx < split_idx < v2_idx
    v1_commit = block.find("conn.commit()", v1_idx)
    assert v1_commit != -1
    assert v1_commit < v2_idx


def test_supabase_grupo_madre_migration_adds_tipo():
    path = (
        Path(__file__).resolve().parents[2]
        / "supabase"
        / "migrations"
        / "20260908000200_grupo_madre_schema.sql"
    )
    sql = path.read_text(encoding="utf-8")
    assert "ADD COLUMN IF NOT EXISTS tipo" in sql
    assert "DROP TABLE" not in sql
    assert "DROP COLUMN" not in sql


def test_init_postgres_schema_sigue_si_falla_madre_v1(monkeypatch):
    db = MagicMock()
    conn = MagicMock()
    cursor = MagicMock()
    conn.cursor.return_value = cursor
    db._connect.return_value = conn
    db._migrar_grupo_madre_v1_si_procede.side_effect = RuntimeError('column "tipo"')
    later = []

    def track_financiero(*_a, **_k):
        later.append("financial")

    monkeypatch.setattr(db, "_migrar_estado_financiero", track_financiero)
    schema_service._init_postgres_schema(db)
    assert later == ["financial"]
    db._migrar_grupo_madre_v2_consolidar_si_procede.assert_called()
