"""Migración reversible: aliados de Grupo Madre → grupo territorial por código postal."""
from __future__ import annotations

import sqlite3
from typing import Any, Dict, List, Optional

from core.db_constants import (
    CP_POSTAL_SENTINEL_MADRE,
    MAX_GRUPOS_POR_CP,
    TIPO_GRUPO_MADRE,
)
from core.repositories.aliado_repo import AliadoRepo
from core.repositories.schema_repo import SchemaRepo
from core.repositories.territorio_repo import TerritorioRepo
from core.services import grupo_service, territorio_service

_repo = TerritorioRepo()
_schema = SchemaRepo()
_aliado_repo = AliadoRepo()

MIGRACION_NOMBRE = "territorio_directo_v1"


def _row_dict(row: Any) -> Dict[str, Any]:
    if row is None:
        return {}
    if hasattr(row, "keys"):
        return dict(row)
    return {}


def _ddl_sqlite(cursor) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS migracion_territorio_backup (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            aliado_id INTEGER NOT NULL,
            codigo TEXT,
            grupo_id_anterior INTEGER,
            grupo_tipo_anterior TEXT,
            codigo_postal TEXT,
            oficio TEXT,
            estado_anterior TEXT,
            grupo_id_nuevo INTEGER,
            caso TEXT NOT NULL,
            detalle TEXT,
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS migracion_territorio_informe (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            aliado_id INTEGER,
            codigo TEXT,
            caso TEXT NOT NULL,
            detalle TEXT,
            codigo_postal TEXT,
            oficio TEXT,
            grupo_id_anterior INTEGER,
            grupo_id_nuevo INTEGER,
            creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


def _ddl_postgres(cursor) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS public.migracion_territorio_backup (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            aliado_id BIGINT NOT NULL,
            codigo TEXT,
            grupo_id_anterior BIGINT,
            grupo_tipo_anterior TEXT,
            codigo_postal TEXT,
            oficio TEXT,
            estado_anterior TEXT,
            grupo_id_nuevo BIGINT,
            caso TEXT NOT NULL,
            detalle TEXT,
            creado_en TIMESTAMPTZ DEFAULT NOW()
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS public.migracion_territorio_informe (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            aliado_id BIGINT,
            codigo TEXT,
            caso TEXT NOT NULL,
            detalle TEXT,
            codigo_postal TEXT,
            oficio TEXT,
            grupo_id_anterior BIGINT,
            grupo_id_nuevo BIGINT,
            creado_en TIMESTAMPTZ DEFAULT NOW()
        )
        """
    )


def asegurar_tablas_migracion(db, cursor) -> None:
    if getattr(db, "backend", None) == "postgres":
        _ddl_postgres(cursor)
    else:
        _ddl_sqlite(cursor)


def _asignar_destino_territorial(
    db, cursor, codigo_postal: str, oficio: str, ciudad: str, provincia: str
) -> Optional[int]:
    cp = (codigo_postal or "").strip()
    of = (oficio or "").strip()
    if not cp:
        return None
    grupos = list(grupo_service._repo.listar_activos_por_cp(cursor, cp))
    for row in grupos:
        g = dict(row) if hasattr(row, "keys") else {"id": row[0]}
        gid = int(g["id"])
        if of and db._grupo_tiene_oficio(cursor, gid, of):
            continue
        return gid
    n = len(grupos)
    if n == 0 or n < MAX_GRUPOS_POR_CP:
        gid = grupo_service._insertar_grupo_nombre_unico(db, cursor, cp, ciudad, provincia)
        _repo.marcar_cp_territorial(cursor, cp, ciudad or cp)
        return int(gid)
    return None


def migrar_madre_a_territorial_cursor(db, cursor) -> Dict[str, Any]:
    """
    Mueve aliados de grupos tipo madre a grupos territoriales de su CP.
    No borra contratos, mensajes ni historial. Conserva columnas históricas.
    """
    asegurar_tablas_migracion(db, cursor)
    resumen = {
        "status": "ok",
        "migrados": 0,
        "sin_codigo_postal": 0,
        "ambiguedad_plaza": 0,
        "grupos_madre_disueltos": 0,
        "casos": 0,
    }
    filas = _repo.listar_aliados_en_grupo_madre(cursor)
    for row in filas:
        data = _row_dict(row)
        aid = int(data.get("aliado_id") or data.get("id") or 0)
        codigo = str(data.get("codigo") or "").strip()
        oficio = str(data.get("oficio") or "").strip()
        estado = str(data.get("estado") or "").strip()
        cp = str(data.get("codigo_postal") or "").strip()
        old_gid = data.get("grupo_id")
        old_gid_i = int(old_gid) if old_gid is not None else None
        tipo_ant = str(data.get("grupo_tipo") or TIPO_GRUPO_MADRE)
        ciudad = str(data.get("grupo_ciudad") or "").strip()
        provincia = str(data.get("grupo_provincia") or "").strip()
        if not aid:
            continue
        if not cp or cp == CP_POSTAL_SENTINEL_MADRE:
            _repo.insertar_backup(
                cursor, aid, codigo, old_gid_i, tipo_ant, cp, oficio, estado,
                None, "sin_codigo_postal", "Aliado en grupo madre sin CP utilizable",
            )
            _repo.insertar_informe(
                cursor, aid, codigo, "sin_codigo_postal",
                "Falta código postal; no se inventa destino",
                cp, oficio, old_gid_i, None,
            )
            resumen["sin_codigo_postal"] += 1
            resumen["casos"] += 1
            continue
        if not ciudad:
            ubic = territorio_service.resolver_ciudad_por_cp(cp) or {}
            ciudad = (ubic.get("ciudad") or "").strip()
            provincia = provincia or (ubic.get("provincia") or "").strip()
        nuevo = _asignar_destino_territorial(db, cursor, cp, oficio, ciudad, provincia)
        if not nuevo:
            _repo.insertar_backup(
                cursor, aid, codigo, old_gid_i, tipo_ant, cp, oficio, estado,
                None, "ambiguedad_plaza",
                "Oficio ocupado en todos los grupos territoriales del CP (tope 5)",
            )
            _repo.insertar_informe(
                cursor, aid, codigo, "ambiguedad_plaza",
                "No hay plaza territorial libre y el CP ya tiene el máximo de grupos",
                cp, oficio, old_gid_i, None,
            )
            resumen["ambiguedad_plaza"] += 1
            resumen["casos"] += 1
            continue
        _aliado_repo.update_grupo_id(cursor, nuevo, aid)
        _repo.marcar_cp_territorial(cursor, cp, ciudad or cp)
        _repo.insertar_backup(
            cursor, aid, codigo, old_gid_i, tipo_ant, cp, oficio, estado,
            nuevo, "migrado", "Asignado a grupo territorial de su código postal",
        )
        _repo.insertar_informe(
            cursor, aid, codigo, "migrado",
            "Asignado al grupo territorial del CP",
            cp, oficio, old_gid_i, nuevo,
        )
        resumen["migrados"] += 1
        resumen["casos"] += 1

    for row in _repo.listar_grupos_madre(cursor):
        g = _row_dict(row)
        gid = int(g.get("id") or 0)
        if not gid:
            continue
        n = _repo.contar_aliados_grupo(cursor, gid)
        if n == 0:
            cursor.execute(
                "UPDATE grupos SET estado = 'disuelto' WHERE id = ? AND estado != 'disuelto'",
                (gid,),
            )
            resumen["grupos_madre_disueltos"] += 1
            _repo.insertar_informe(
                cursor, None, "", "grupo_madre_vacio",
                f"Grupo madre {gid} disuelto al quedar sin aliados",
                str(g.get("codigo_postal") or ""), "", gid, None,
            )
            resumen["casos"] += 1
        else:
            _repo.insertar_informe(
                cursor, None, "", "grupo_madre_residual",
                f"Grupo madre {gid} conserva {n} aliados (casos del informe)",
                str(g.get("codigo_postal") or ""), "", gid, None,
            )
            resumen["casos"] += 1
    return resumen


def migrar_madre_a_territorial(db) -> Dict[str, Any]:
    with db._lock:
        conn = None
        try:
            conn = db._connect()
            cursor = conn.cursor()
            result = migrar_madre_a_territorial_cursor(db, cursor)
            conn.commit()
            return result
        except Exception as e:
            if conn:
                conn.rollback()
            return {"status": "error", "message": str(e)}
        finally:
            if conn:
                conn.close()


def revertir_migracion_territorio_cursor(db, cursor) -> Dict[str, Any]:
    """Restaura grupo_id desde el backup de filas migradas. No toca el resto de datos."""
    asegurar_tablas_migracion(db, cursor)
    restaurados = 0
    for row in _repo.listar_backup_migrados(cursor):
        data = _row_dict(row)
        aid = int(data.get("aliado_id") or 0)
        old_gid = data.get("grupo_id_anterior")
        if not aid:
            continue
        _aliado_repo.update_grupo_id(cursor, old_gid, aid)
        if old_gid is not None:
            cursor.execute(
                "UPDATE grupos SET estado = 'activo' WHERE id = ?",
                (int(old_gid),),
            )
        restaurados += 1
    return {"status": "ok", "restaurados": restaurados}


def revertir_migracion_territorio(db) -> Dict[str, Any]:
    with db._lock:
        conn = None
        try:
            conn = db._connect()
            cursor = conn.cursor()
            result = revertir_migracion_territorio_cursor(db, cursor)
            conn.commit()
            return result
        except Exception as e:
            if conn:
                conn.rollback()
            return {"status": "error", "message": str(e)}
        finally:
            if conn:
                conn.close()


def comprobar_migracion(db) -> Dict[str, Any]:
    """Aliados activos/pendientes sin grupo territorial válido."""
    with db._lock:
        conn = None
        try:
            conn = db._connect()
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            asegurar_tablas_migracion(db, cursor)
            filas = [_row_dict(r) for r in _repo.listar_sin_grupo_territorial_valido(cursor)]
            informe = [_row_dict(r) for r in _repo.listar_informe(cursor)]
            return {
                "status": "success",
                "sin_grupo_territorial_valido": filas,
                "total": len(filas),
                "informe": informe,
            }
        except Exception as e:
            return {"status": "error", "message": str(e), "sin_grupo_territorial_valido": [], "total": 0}
        finally:
            if conn:
                conn.close()


def listar_estado_territorial(db, limite: int = 500) -> Dict[str, Any]:
    with db._lock:
        conn = None
        try:
            conn = db._connect()
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            filas = [_row_dict(r) for r in _repo.listar_estado_territorial_aliados(cursor, limite)]
            return {"status": "success", "aliados": filas, "total": len(filas)}
        except Exception as e:
            return {"status": "error", "message": str(e), "aliados": [], "total": 0}
        finally:
            if conn:
                conn.close()
