"""Tipos de discrepancia financiera (FASE 02)."""
from __future__ import annotations

from enum import Enum


class TipoDiscrepancia(str, Enum):
    PAYMENT_MISSING_STRIPE = "PAYMENT_MISSING_STRIPE"
    PAYMENT_MISSING_RUANA = "PAYMENT_MISSING_RUANA"
    TRANSFER_MISSING_STRIPE = "TRANSFER_MISSING_STRIPE"
    TRANSFER_MISSING_RUANA = "TRANSFER_MISSING_RUANA"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    STATUS_MISMATCH = "STATUS_MISMATCH"
    TRANSFER_ID_MISMATCH = "TRANSFER_ID_MISMATCH"
    PAYMENT_INTENT_MISMATCH = "PAYMENT_INTENT_MISMATCH"
    REFUND_MISSING_STRIPE = "REFUND_MISSING_STRIPE"
    REFUND_MISSING_RUANA = "REFUND_MISSING_RUANA"
    REFUND_AMOUNT_MISMATCH = "REFUND_AMOUNT_MISMATCH"
    REFUND_DUPLICATE = "REFUND_DUPLICATE"
    REFUND_COMMISSION_MISMATCH = "REFUND_COMMISSION_MISMATCH"
    DISPUTE_MISSING_STRIPE = "DISPUTE_MISSING_STRIPE"
    DISPUTE_MISSING_RUANA = "DISPUTE_MISSING_RUANA"
    DISPUTE_AMOUNT_MISMATCH = "DISPUTE_AMOUNT_MISMATCH"
    DISPUTE_STATUS_MISMATCH = "DISPUTE_STATUS_MISMATCH"
    DISPUTE_DEADLINE_MISMATCH = "DISPUTE_DEADLINE_MISMATCH"
    DISPUTE_FUNDS_MISMATCH = "DISPUTE_FUNDS_MISMATCH"
    DISPUTE_REFUND_INCOMPATIBLE = "DISPUTE_REFUND_INCOMPATIBLE"
    DISPUTE_TRANSFER_INCOMPATIBLE = "DISPUTE_TRANSFER_INCOMPATIBLE"
    UNKNOWN = "UNKNOWN"
