"""Tipos de discrepancia financiera (FASE 02)."""
from __future__ import annotations

from enum import Enum


class TipoDiscrepancia(str, Enum):
    PAYMENT_MISSING_STRIPE = "PAYMENT_MISSING_STRIPE"
    PAYMENT_MISSING_RUANA = "PAYMENT_MISSING_RUANA"
    TRANSFER_MISSING_STRIPE = "TRANSFER_MISSING_STRIPE"
    TRANSFER_MISSING_RUANA = "TRANSFER_MISSING_RUANA"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    STATUS_MISMATCH = "STATUS_MISMATCH"
    TRANSFER_ID_MISMATCH = "TRANSFER_ID_MISMATCH"
    PAYMENT_INTENT_MISMATCH = "PAYMENT_INTENT_MISMATCH"
    UNKNOWN = "UNKNOWN"
