"""Tipos de transacción del ledger (FASE 08)."""
from __future__ import annotations

from enum import Enum


class TipoLedgerTransaction(str, Enum):
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PAYMENT_SETTLED = "PAYMENT_SETTLED"
    OBLIGATION_RECOGNIZED = "OBLIGATION_RECOGNIZED"
    TRANSFER_OUT = "TRANSFER_OUT"
    TRANSFER_SETTLED = "TRANSFER_SETTLED"
    TRANSFER_REVERSED = "TRANSFER_REVERSED"
    REFUND_OBLIGATION = "REFUND_OBLIGATION"
    REFUND_SETTLED = "REFUND_SETTLED"
    DISPUTE_OPENED = "DISPUTE_OPENED"
    DISPUTE_LOSS = "DISPUTE_LOSS"
    DISPUTE_FUNDS_REINSTATED = "DISPUTE_FUNDS_REINSTATED"
    STRIPE_FEE = "STRIPE_FEE"
    ADMIN_ADJUSTMENT = "ADMIN_ADJUSTMENT"
    VOID_COMPENSATION = "VOID_COMPENSATION"
