-- RUANA clean Supabase schema.
-- Apply from Supabase SQL Editor or with the Supabase CLI once DATABASE_URL is available.

create extension if not exists pgcrypto;
create extension if not exists citext;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'aliado' check (role in ('aliado', 'admin')),
  aliado_codigo text unique,
  admin_codigo text unique,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.current_aliado_codigo()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.aliado_codigo
  from public.profiles p
  where p.id = auth.uid()
  limit 1
$$;

create or replace function public.is_ruana_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
$$;

create table if not exists public.grupos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  codigo_postal text not null,
  ciudad text,
  provincia text,
  estado text not null default 'activo' check (estado in ('activo', 'en_competencia', 'disuelto')),
  created_at timestamptz not null default now()
);

create table if not exists public.aliados (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  codigo text not null unique,
  nombre text not null,
  marca text,
  oficio text,
  codigo_postal text,
  grupo_id bigint references public.grupos(id) on delete set null,
  email citext unique,
  telefono text unique,
  estado text not null default 'activo',
  score integer not null default 0 check (score >= 0 and score <= 100),
  especializaciones jsonb not null default '[]'::jsonb,
  descripcion_servicio text,
  derrotas_competencia integer not null default 0,
  qr_paypal_path text,
  bizum_num text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger aliados_set_updated_at
before update on public.aliados
for each row execute function public.set_updated_at();

create table if not exists public.solicitudes (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.grupos(id) on delete restrict,
  solicitante_codigo text not null references public.aliados(codigo) on delete restrict,
  solicitante_nombre text not null,
  oficio text not null,
  descripcion text,
  estado text not null default 'pendiente',
  atendido_por_codigo text references public.aliados(codigo) on delete set null,
  atendido_por_nombre text,
  created_at timestamptz not null default now(),
  atendido_at timestamptz
);

create table if not exists public.contactos_ruana (
  id bigint generated by default as identity primary key,
  solicitante_codigo text not null references public.aliados(codigo) on delete restrict,
  profesional_codigo text not null references public.aliados(codigo) on delete restrict,
  servicio text,
  estado text not null,
  pendiente_resolucion boolean not null default true,
  contacto_externo_habilitado boolean not null default false,
  importe_solicitante numeric(12,2),
  importe_solicitante_moneda text,
  declarado_por_solicitante text,
  fecha_declaracion_solicitante timestamptz,
  importe_profesional numeric(12,2),
  importe_profesional_moneda text,
  declarado_por_profesional text,
  fecha_declaracion_profesional timestamptz,
  importe_final numeric(12,2),
  comision numeric(12,2),
  comision_porcentaje numeric(6,4) not null default 0.05,
  apoyo_ruana numeric(12,2),
  estado_pago text not null default 'no_generado',
  pendiente_pago boolean not null default false,
  comprobante_ruta text,
  posponer_recordatorio boolean not null default false,
  fecha_pospuesto_hasta timestamptz,
  motivo_contacto text,
  fecha_validacion_pago timestamptz,
  admin_validacion_codigo text,
  motivo_rechazo_pago text,
  fraude_sospechado boolean not null default false,
  fraude_confirmado boolean not null default false,
  fraude_motivo text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  fecha_aceptacion timestamptz,
  fecha_trabajo_en_progreso timestamptz,
  fecha_cierre timestamptz,
  fecha_no_concretado timestamptz,
  fecha_disputa timestamptz
);

create trigger contactos_ruana_set_updated_at
before update on public.contactos_ruana
for each row execute function public.set_updated_at();

create table if not exists public.chat_mensajes (
  id bigint generated by default as identity primary key,
  contacto_id bigint not null references public.contactos_ruana(id) on delete cascade,
  emisor_codigo text not null references public.aliados(codigo) on delete restrict,
  texto text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contacto_panel_oculto (
  contacto_id bigint not null references public.contactos_ruana(id) on delete cascade,
  codigo_aliado text not null references public.aliados(codigo) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (contacto_id, codigo_aliado)
);

create table if not exists public.contacto_penalizaciones_aplicadas (
  contacto_id bigint not null references public.contactos_ruana(id) on delete cascade,
  tipo text not null,
  aplicado_en timestamptz not null default now(),
  primary key (contacto_id, tipo)
);

create table if not exists public.confirmaciones_trabajo (
  id bigint generated by default as identity primary key,
  contacto_id bigint not null references public.contactos_ruana(id) on delete cascade,
  aliado_id bigint not null references public.aliados(id) on delete cascade,
  importe_declarado numeric(12,2) not null,
  created_at timestamptz not null default now(),
  unique (contacto_id, aliado_id)
);

create table if not exists public.payment_conflicts (
  id bigint generated by default as identity primary key,
  trabajo_id bigint not null references public.contactos_ruana(id) on delete cascade,
  contratante_id bigint not null references public.aliados(id) on delete restrict,
  profesional_id bigint not null references public.aliados(id) on delete restrict,
  importe_contratante numeric(12,2) not null,
  importe_profesional numeric(12,2) not null,
  estado text not null default 'PENDIENTE_PRUEBA',
  prueba_url text,
  comentario_admin text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger payment_conflicts_set_updated_at
before update on public.payment_conflicts
for each row execute function public.set_updated_at();

create table if not exists public.ingresos_ruana (
  id bigint generated by default as identity primary key,
  contacto_id bigint not null references public.contactos_ruana(id) on delete cascade,
  importe_final numeric(12,2) not null,
  apoyo_ruana numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.score_movimientos (
  id bigint generated by default as identity primary key,
  codigo_aliado text not null references public.aliados(codigo) on delete cascade,
  delta integer not null,
  motivo text,
  created_at timestamptz not null default now()
);

create table if not exists public.evaluaciones (
  id bigint generated by default as identity primary key,
  codigo_aliado text not null unique references public.aliados(codigo) on delete cascade,
  estado text not null,
  score numeric(6,2) not null default 0,
  intencion text,
  tasa_respuesta numeric(6,2) not null default 0,
  tasa_confirmacion numeric(6,2) not null default 0,
  meses_sin_trabajo integer not null default 0,
  ciclos_consecutivos integer not null default 1,
  razones jsonb not null default '[]'::jsonb,
  severidad text not null default 'normal',
  evaluated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger evaluaciones_set_updated_at
before update on public.evaluaciones
for each row execute function public.set_updated_at();

create table if not exists public.evaluaciones_historico (
  id bigint generated by default as identity primary key,
  codigo_aliado text not null references public.aliados(codigo) on delete cascade,
  estado_anterior text,
  estado_nuevo text not null,
  score_anterior numeric(6,2),
  score_nuevo numeric(6,2),
  razon_cambio text,
  created_at timestamptz not null default now()
);

create table if not exists public.invitaciones (
  codigo text primary key,
  invitador_aliado_id bigint not null references public.aliados(id) on delete cascade,
  usado boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.referidos (
  codigo_referido text primary key references public.aliados(codigo) on delete cascade,
  codigo_invitador text not null references public.aliados(codigo) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.invitaciones_oficio (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  grupo_id bigint not null references public.grupos(id) on delete cascade,
  oficio text not null,
  aliado_id bigint not null references public.aliados(id) on delete cascade,
  estado text not null default 'pendiente',
  created_at timestamptz not null default now()
);

create table if not exists public.notificaciones_aliado (
  id bigint generated by default as identity primary key,
  aliado_codigo text not null references public.aliados(codigo) on delete cascade,
  tipo text not null,
  titulo text,
  mensaje text not null,
  metadata jsonb not null default '{}'::jsonb,
  leida boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.competencia (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.grupos(id) on delete cascade,
  oficio text not null,
  aliado_original_codigo text not null references public.aliados(codigo) on delete restrict,
  suplente_codigo text not null references public.aliados(codigo) on delete restrict,
  suplente_grupo_anterior_id bigint references public.grupos(id) on delete set null,
  fecha_inicio timestamptz not null default now(),
  fecha_fin_prevista timestamptz not null,
  estado text not null default 'activa' check (estado in ('activa', 'finalizada')),
  ganador_codigo text references public.aliados(codigo) on delete set null,
  score_titular_inicio integer,
  score_suplente_inicio integer,
  score_titular_actual integer,
  score_suplente_actual integer,
  motivo text,
  created_at timestamptz not null default now()
);

create table if not exists public.avisos_grupo (
  id bigint generated by default as identity primary key,
  grupo_id bigint not null references public.grupos(id) on delete cascade,
  tipo text not null,
  texto text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.grupo_oficio_cerrado (
  grupo_id bigint not null references public.grupos(id) on delete cascade,
  oficio text not null,
  cerrado_en timestamptz not null default now(),
  primary key (grupo_id, oficio)
);

create table if not exists public.eventos_sistema (
  id bigint generated by default as identity primary key,
  tipo text not null,
  descripcion text not null,
  actor_tipo text,
  actor_codigo text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  entidad text not null,
  entidad_id bigint,
  accion text not null,
  actor_tipo text,
  actor_codigo text,
  detalles jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_aliados_codigo on public.aliados(codigo);
create index if not exists idx_aliados_postal on public.aliados(codigo_postal);
create index if not exists idx_aliados_auth_user_id on public.aliados(auth_user_id);
create index if not exists idx_grupos_nombre on public.grupos(nombre);
create index if not exists idx_grupos_cp_estado on public.grupos(codigo_postal, estado);
create index if not exists idx_solicitudes_grupo on public.solicitudes(grupo_id);
create index if not exists idx_solicitudes_estado on public.solicitudes(estado);
create index if not exists idx_solicitudes_created on public.solicitudes(created_at desc);
create index if not exists idx_contactos_profesional on public.contactos_ruana(profesional_codigo);
create index if not exists idx_contactos_solicitante on public.contactos_ruana(solicitante_codigo);
create index if not exists idx_contactos_estado on public.contactos_ruana(estado);
create index if not exists idx_contactos_pendiente on public.contactos_ruana(pendiente_resolucion);
create index if not exists idx_chat_mensajes_contacto on public.chat_mensajes(contacto_id);
create index if not exists idx_chat_mensajes_created on public.chat_mensajes(created_at desc);
create index if not exists idx_score_movimientos_codigo on public.score_movimientos(codigo_aliado);
create index if not exists idx_score_movimientos_created on public.score_movimientos(created_at);
create index if not exists idx_notificaciones_aliado_codigo on public.notificaciones_aliado(aliado_codigo);
create index if not exists idx_notificaciones_aliado_created on public.notificaciones_aliado(created_at desc);
create index if not exists idx_competencia_grupo_estado on public.competencia(grupo_id, estado);
create index if not exists idx_competencia_fin on public.competencia(fecha_fin_prevista, estado);
create index if not exists idx_payment_conflicts_trabajo on public.payment_conflicts(trabajo_id);
create index if not exists idx_payment_conflicts_created on public.payment_conflicts(created_at desc);
create index if not exists idx_eventos_sistema_created on public.eventos_sistema(created_at desc);
create index if not exists idx_audit_log_entidad on public.audit_log(entidad, entidad_id);

alter table public.profiles enable row level security;
alter table public.grupos enable row level security;
alter table public.aliados enable row level security;
alter table public.solicitudes enable row level security;
alter table public.contactos_ruana enable row level security;
alter table public.chat_mensajes enable row level security;
alter table public.contacto_panel_oculto enable row level security;
alter table public.contacto_penalizaciones_aplicadas enable row level security;
alter table public.confirmaciones_trabajo enable row level security;
alter table public.payment_conflicts enable row level security;
alter table public.ingresos_ruana enable row level security;
alter table public.score_movimientos enable row level security;
alter table public.evaluaciones enable row level security;
alter table public.evaluaciones_historico enable row level security;
alter table public.invitaciones enable row level security;
alter table public.referidos enable row level security;
alter table public.invitaciones_oficio enable row level security;
alter table public.notificaciones_aliado enable row level security;
alter table public.competencia enable row level security;
alter table public.avisos_grupo enable row level security;
alter table public.grupo_oficio_cerrado enable row level security;
alter table public.eventos_sistema enable row level security;
alter table public.audit_log enable row level security;

create policy "profiles_select_self_or_admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_ruana_admin());

create policy "aliados_select_self_or_admin"
on public.aliados for select
to authenticated
using (auth_user_id = auth.uid() or public.is_ruana_admin());

create policy "aliados_update_self_or_admin"
on public.aliados for update
to authenticated
using (auth_user_id = auth.uid() or public.is_ruana_admin())
with check (auth_user_id = auth.uid() or public.is_ruana_admin());

create policy "notificaciones_select_self_or_admin"
on public.notificaciones_aliado for select
to authenticated
using (aliado_codigo = public.current_aliado_codigo() or public.is_ruana_admin());

create policy "notificaciones_update_self_or_admin"
on public.notificaciones_aliado for update
to authenticated
using (aliado_codigo = public.current_aliado_codigo() or public.is_ruana_admin())
with check (aliado_codigo = public.current_aliado_codigo() or public.is_ruana_admin());

create policy "contactos_select_participants_or_admin"
on public.contactos_ruana for select
to authenticated
using (
  public.is_ruana_admin()
  or public.current_aliado_codigo() in (solicitante_codigo, profesional_codigo)
);

create policy "chat_select_participants_or_admin"
on public.chat_mensajes for select
to authenticated
using (
  public.is_ruana_admin()
  or exists (
    select 1
    from public.contactos_ruana c
    where c.id = chat_mensajes.contacto_id
      and public.current_aliado_codigo() in (c.solicitante_codigo, c.profesional_codigo)
  )
);

create policy "chat_insert_participants_or_admin"
on public.chat_mensajes for insert
to authenticated
with check (
  public.is_ruana_admin()
  or (
    emisor_codigo = public.current_aliado_codigo()
    and exists (
      select 1
      from public.contactos_ruana c
      where c.id = chat_mensajes.contacto_id
        and public.current_aliado_codigo() in (c.solicitante_codigo, c.profesional_codigo)
    )
  )
);

create policy "admin_read_all_grupos" on public.grupos for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_solicitudes" on public.solicitudes for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_score" on public.score_movimientos for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_evaluaciones" on public.evaluaciones for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_evaluaciones_historico" on public.evaluaciones_historico for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_competencia" on public.competencia for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_payment_conflicts" on public.payment_conflicts for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_eventos" on public.eventos_sistema for select to authenticated using (public.is_ruana_admin());
create policy "admin_read_all_audit" on public.audit_log for select to authenticated using (public.is_ruana_admin());

insert into storage.buckets (id, name, public)
values
  ('ruana-public', 'ruana-public', true),
  ('ruana-comprobantes', 'ruana-comprobantes', false),
  ('ruana-conflictos', 'ruana-conflictos', false)
on conflict (id) do nothing;

create policy "storage_public_read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'ruana-public');

create policy "storage_private_authenticated_insert"
on storage.objects for insert
to authenticated
with check (bucket_id in ('ruana-comprobantes', 'ruana-conflictos'));

create policy "storage_private_owner_or_admin_read"
on storage.objects for select
to authenticated
using (
  bucket_id in ('ruana-comprobantes', 'ruana-conflictos')
  and (owner = auth.uid() or public.is_ruana_admin())
);

alter table public.chat_mensajes replica identity full;
alter table public.notificaciones_aliado replica identity full;
alter table public.contactos_ruana replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.chat_mensajes;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.notificaciones_aliado;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.contactos_ruana;
exception when duplicate_object then null;
end $$;
