-- Territorio directo por código postal.
-- Conserva columnas históricas de Grupo Madre (tipo, grupo_madre_id, cp_estado.modo).
-- No DROP de tablas ni columnas. Backup reversible en migracion_territorio_*.

CREATE TABLE IF NOT EXISTS public.migracion_territorio_backup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aliado_id BIGINT NOT NULL,
    codigo TEXT,
    grupo_id_anterior BIGINT,
    grupo_tipo_anterior TEXT,
    codigo_postal TEXT,
    oficio TEXT,
    estado_anterior TEXT,
    grupo_id_nuevo BIGINT,
    caso TEXT NOT NULL,
    detalle TEXT,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.migracion_territorio_informe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aliado_id BIGINT,
    codigo TEXT,
    caso TEXT NOT NULL,
    detalle TEXT,
    codigo_postal TEXT,
    oficio TEXT,
    grupo_id_anterior BIGINT,
    grupo_id_nuevo BIGINT,
    creado_en TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO public.migraciones (nombre)
VALUES ('territorio_directo_v1')
ON CONFLICT (nombre) DO NOTHING;
