-- Archivo de aliados eliminados definitivamente (un registro de auditoría por eliminación).
-- Los datos operativos se purgan; email, teléfono y código quedan liberados en aliados.

create table if not exists public.aliados_eliminados (
  id bigint generated by default as identity primary key,
  codigo text not null,
  nombre text,
  marca text,
  oficio text,
  codigo_postal text,
  email text,
  telefono text,
  estado_anterior text,
  motivo text,
  admin_codigo text,
  eliminado_en timestamptz not null default now()
);

create index if not exists idx_aliados_eliminados_codigo on public.aliados_eliminados(codigo);
create index if not exists idx_aliados_eliminados_fecha on public.aliados_eliminados(eliminado_en desc);
