-- RUANA: sincroniza el esquema PostgreSQL usado por el panel del aliado.
-- Idempotente: no elimina datos y conserva nombres legacy cuando existen.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.competencia') IS NOT NULL
     AND EXISTS (
       SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = 'competencia'
         AND column_name = 'suplente_codigo'
     )
     AND NOT EXISTS (
       SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = 'competencia'
         AND column_name = 'retador_codigo'
     ) THEN
    ALTER TABLE public.competencia RENAME COLUMN suplente_codigo TO retador_codigo;
  END IF;

  IF to_regclass('public.competencia') IS NOT NULL
     AND EXISTS (
       SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = 'competencia'
         AND column_name = 'suplente_grupo_anterior_id'
     )
     AND NOT EXISTS (
       SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = 'competencia'
         AND column_name = 'retador_grupo_anterior_id'
     ) THEN
    ALTER TABLE public.competencia
      RENAME COLUMN suplente_grupo_anterior_id TO retador_grupo_anterior_id;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.competencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_id BIGINT NOT NULL REFERENCES public.grupos(id),
  oficio TEXT NOT NULL,
  aliado_original_codigo TEXT NOT NULL REFERENCES public.aliados(codigo),
  retador_codigo TEXT NOT NULL REFERENCES public.aliados(codigo),
  retador_grupo_anterior_id BIGINT,
  fecha_inicio TIMESTAMPTZ DEFAULT NOW(),
  fecha_fin_prevista TIMESTAMPTZ NOT NULL,
  estado TEXT DEFAULT 'activa',
  ganador_codigo TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS fecha_cierre TIMESTAMPTZ;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS score_titular_inicio INTEGER;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS score_retador_inicio INTEGER;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS score_titular_actual INTEGER;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS score_retador_actual INTEGER;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS score_titular_final INTEGER;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS score_retador_final INTEGER;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS motivo TEXT;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS retador_codigo TEXT;
ALTER TABLE public.competencia ADD COLUMN IF NOT EXISTS retador_grupo_anterior_id BIGINT;

CREATE TABLE IF NOT EXISTS public.competencia_pendiente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aliado_codigo TEXT NOT NULL REFERENCES public.aliados(codigo),
  grupo_id BIGINT NOT NULL REFERENCES public.grupos(id),
  oficio TEXT NOT NULL,
  codigo_postal TEXT NOT NULL,
  score_al_crear INTEGER,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_competencia_pendiente_cp_oficio
  ON public.competencia_pendiente(codigo_postal, oficio, estado);

ALTER TABLE public.payment_conflicts
  ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'importe_discrepante';

COMMIT;
