-- Grupo Madre por ciudad + tablas de incubación.
-- La consolidación de aliados existentes (pasar grupos territoriales
-- pequeños al madre) la aplica el backend al arrancar (grupo_madre_v2_consolidar).

ALTER TABLE IF EXISTS public.grupos
  ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'territorial';

ALTER TABLE IF EXISTS public.grupos
  ADD COLUMN IF NOT EXISTS grupo_madre_id BIGINT REFERENCES public.grupos(id);

UPDATE public.grupos
SET tipo = 'territorial'
WHERE tipo IS NULL OR btrim(tipo) = '';

CREATE TABLE IF NOT EXISTS public.migraciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT UNIQUE NOT NULL,
  aplicada_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cp_ciudad (
  codigo_postal TEXT PRIMARY KEY,
  ciudad TEXT NOT NULL,
  provincia TEXT,
  normalizado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.cp_estado (
  codigo_postal TEXT PRIMARY KEY,
  ciudad TEXT NOT NULL,
  modo TEXT NOT NULL DEFAULT 'incubacion'
    CHECK (modo IN ('incubacion', 'territorial')),
  grupo_madre_id BIGINT REFERENCES public.grupos(id),
  aliados_activos INTEGER DEFAULT 0,
  encargos_validos INTEGER DEFAULT 0,
  listo_independizar INTEGER DEFAULT 0,
  independizado_en TIMESTAMPTZ,
  actualizado_en TIMESTAMPTZ DEFAULT NOW(),
  aliados_desde_ultimo_grupo INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.cp_independencia_solicitudes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_postal TEXT NOT NULL,
  ciudad TEXT NOT NULL,
  aliados_activos INTEGER NOT NULL,
  encargos_validos INTEGER NOT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aprobada', 'pospuesta')),
  notas_admin TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW(),
  resuelto_en TIMESTAMPTZ,
  resuelto_por TEXT
);

CREATE TABLE IF NOT EXISTS public.aliado_avisos_vistos (
  aliado_codigo TEXT NOT NULL,
  aviso_tipo TEXT NOT NULL,
  visto_en TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (aliado_codigo, aviso_tipo)
);
