-- Crecimiento orgánico de grupos profesionales

alter table if exists public.invitaciones
  add column if not exists grupo_id bigint references public.grupos(id) on delete set null;

alter table if exists public.invitaciones
  add column if not exists tipo text default 'ampliar_red';

create index if not exists idx_invitaciones_grupo_id on public.invitaciones(grupo_id);
create index if not exists idx_invitaciones_tipo on public.invitaciones(tipo);

create table if not exists public.grupo_crecimiento_recompensas (
  id bigint generated by default as identity primary key,
  invitador_codigo text not null references public.aliados(codigo) on delete cascade,
  invitado_codigo text not null references public.aliados(codigo) on delete cascade,
  invitacion_codigo text,
  grupo_id bigint references public.grupos(id) on delete set null,
  score_delta integer not null default 5,
  creado_en timestamptz not null default now(),
  unique (invitador_codigo, invitado_codigo)
);

create index if not exists idx_gcr_invitador on public.grupo_crecimiento_recompensas(invitador_codigo);
